# Starter pipeline

#trigger:
#- master


trigger:
  branches:
    include:
    - master
    - release
    - dev

resources:
- repo: self
queue:
  name: zllzh
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
   mkdir sync
   cd sync
   git clone https://github.com/zllzh/z.git

   git remote add azure ssh://tsdevops.telsafe.com.cn:22/tfs/ProductCollection/ScrumTemplate/_git/z
   git push azure master --force
  displayName: 'Run a multi-line script'


