# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'zllzh'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    mkdir sync
    cd sync
    git clone  https://github.com/zllzh/zllzh-CI.git
    cd <github project>
    git remote add azure https://<Azure DevOps Organization>:<token>@dev.azure.com/<Azure DevOps Organization>/<project>/_git/<repo.git> 8    
    git push -u azure $(branch) --force
  displayName: 'Run a multi-line script'
